import './jvectormap.js';
import createJVectorMap from './jquery-jvectormap.js';
import './abstract-element.js';
import './abstract-canvas-element.js';
import './abstract-shape-element.js';
import './svg-element.js';
import './svg-group-element.js';
import './svg-canvas-element.js';
import './svg-shape-element.js';
import './svg-path-element.js';
import './svg-circle-element.js';
import './svg-image-element.js';
import './svg-text-element.js';
import './vml-element.js';
import './vml-group-element.js';
import './vml-canvas-element.js';
import './vml-shape-element.js';
import './vml-path-element.js';
import './vml-circle-element.js';
import './vml-image-element.js';
import './vector-canvas.js';
import './simple-scale.js';
import './ordinal-scale.js';
import './numeric-scale.js';
import './color-scale.js';
import './legend.js';
import './data-series.js';
import './proj.js';
import './map-object.js';
import './region.js';
import './marker.js';
import './map.js';
import './multimap.js';

export default createJVectorMap;
